/**
 * Preloaded starter files per stack part. These are written verbatim instead of
 * being generated by the model, which saves tokens and keeps setup files correct.
 */
import type { PlanFile, StackOption } from "./types";

type Scaffold = { path: string; description: string; task: PlanFile["task"]; content: string };

const j = (v: unknown) => JSON.stringify(v, null, 2) + "\n";

const SHADCN_DEPS = {
  "@radix-ui/react-slot": "^1.1.0",
  "class-variance-authority": "^0.7.0",
  clsx: "^2.1.1",
  "lucide-react": "^0.441.0",
  "tailwind-merge": "^2.5.2",
};

const UTILS = `import { clsx, type ClassValue } from "clsx";
import { twMerge } from "tailwind-merge";

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}
`;

const BUTTON = (utils: string) => `import * as React from "react";
import { Slot } from "@radix-ui/react-slot";
import { cva, type VariantProps } from "class-variance-authority";
import { cn } from "${utils}";

const buttonVariants = cva(
  "inline-flex items-center justify-center gap-2 whitespace-nowrap rounded-md text-sm font-medium transition-colors focus-visible:outline-none focus-visible:ring-2 disabled:pointer-events-none disabled:opacity-50",
  {
    variants: {
      variant: {
        default: "bg-slate-900 text-white hover:bg-slate-800",
        secondary: "bg-slate-100 text-slate-900 hover:bg-slate-200",
        outline: "border border-slate-300 bg-white hover:bg-slate-50",
        ghost: "hover:bg-slate-100",
        destructive: "bg-red-600 text-white hover:bg-red-700",
      },
      size: { default: "h-10 px-4 py-2", sm: "h-9 px-3", lg: "h-11 px-8", icon: "h-10 w-10" },
    },
    defaultVariants: { variant: "default", size: "default" },
  },
);

export interface ButtonProps
  extends React.ButtonHTMLAttributes<HTMLButtonElement>,
    VariantProps<typeof buttonVariants> {
  asChild?: boolean;
}

export const Button = React.forwardRef<HTMLButtonElement, ButtonProps>(
  ({ className, variant, size, asChild = false, ...props }, ref) => {
    const Comp = asChild ? Slot : "button";
    return <Comp className={cn(buttonVariants({ variant, size, className }))} ref={ref} {...props} />;
  },
);
Button.displayName = "Button";
export { buttonVariants };
`;

const CARD = (utils: string) => `import * as React from "react";
import { cn } from "${utils}";

export function Card({ className, ...props }: React.HTMLAttributes<HTMLDivElement>) {
  return <div className={cn("rounded-xl border border-slate-200 bg-white shadow-sm", className)} {...props} />;
}
export function CardHeader({ className, ...props }: React.HTMLAttributes<HTMLDivElement>) {
  return <div className={cn("flex flex-col gap-1.5 p-6", className)} {...props} />;
}
export function CardTitle({ className, ...props }: React.HTMLAttributes<HTMLHeadingElement>) {
  return <h3 className={cn("text-lg font-semibold leading-none", className)} {...props} />;
}
export function CardDescription({ className, ...props }: React.HTMLAttributes<HTMLParagraphElement>) {
  return <p className={cn("text-sm text-slate-500", className)} {...props} />;
}
export function CardContent({ className, ...props }: React.HTMLAttributes<HTMLDivElement>) {
  return <div className={cn("p-6 pt-0", className)} {...props} />;
}
export function CardFooter({ className, ...props }: React.HTMLAttributes<HTMLDivElement>) {
  return <div className={cn("flex items-center p-6 pt-0", className)} {...props} />;
}
`;

const INPUT = (utils: string) => `import * as React from "react";
import { cn } from "${utils}";

export const Input = React.forwardRef<HTMLInputElement, React.InputHTMLAttributes<HTMLInputElement>>(
  ({ className, ...props }, ref) => (
    <input
      ref={ref}
      className={cn("flex h-10 w-full rounded-md border border-slate-300 bg-white px-3 py-2 text-sm outline-none focus:ring-2 focus:ring-slate-400", className)}
      {...props}
    />
  ),
);
Input.displayName = "Input";
`;

const TAILWIND_CSS = `@tailwind base;
@tailwind components;
@tailwind utilities;

body { @apply bg-slate-50 text-slate-900 antialiased; }
`;

function reactScaffold(): Scaffold[] {
  return [
    {
      path: "frontend/package.json",
      description: "Frontend dependencies and scripts",
      task: "config_file",
      content: j({
        name: "frontend",
        private: true,
        type: "module",
        scripts: { dev: "vite", build: "tsc -b && vite build", preview: "vite preview" },
        dependencies: {
          react: "^18.3.1",
          "react-dom": "^18.3.1",
          "react-router-dom": "^6.26.2",
          "@tanstack/react-query": "^5.56.2",
          ...SHADCN_DEPS,
        },
        devDependencies: {
          "@types/react": "^18.3.5",
          "@types/react-dom": "^18.3.0",
          "@vitejs/plugin-react": "^4.3.1",
          autoprefixer: "^10.4.20",
          postcss: "^8.4.47",
          tailwindcss: "^3.4.11",
          typescript: "^5.5.3",
          vite: "^5.4.5",
        },
      }),
    },
    {
      path: "frontend/vite.config.ts",
      description: "Vite config with @ alias and API proxy",
      task: "config_file",
      content: `import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
import path from "path";

export default defineConfig({
  plugins: [react()],
  resolve: { alias: { "@": path.resolve(__dirname, "src") } },
  server: { port: 5173, proxy: { "/api": "http://localhost:8000" } },
});
`,
    },
    {
      path: "frontend/tsconfig.json",
      description: "TypeScript config",
      task: "config_file",
      content: j({
        compilerOptions: {
          target: "ES2020",
          lib: ["ES2020", "DOM", "DOM.Iterable"],
          module: "ESNext",
          moduleResolution: "bundler",
          jsx: "react-jsx",
          strict: true,
          skipLibCheck: true,
          noEmit: true,
          baseUrl: ".",
          paths: { "@/*": ["src/*"] },
        },
        include: ["src"],
      }),
    },
    {
      path: "frontend/tailwind.config.js",
      description: "Tailwind config",
      task: "config_file",
      content: `/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: { extend: {} },
  plugins: [],
};
`,
    },
    {
      path: "frontend/postcss.config.js",
      description: "PostCSS config",
      task: "config_file",
      content: `export default { plugins: { tailwindcss: {}, autoprefixer: {} } };\n`,
    },
    {
      path: "frontend/index.html",
      description: "HTML entry",
      task: "config_file",
      content: `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>App</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.tsx"></script>
  </body>
</html>
`,
    },
    {
      path: "frontend/src/main.tsx",
      description: "React entry point",
      task: "frontend_file",
      content: `import React from "react";
import ReactDOM from "react-dom/client";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import App from "./App";
import "./index.css";

const queryClient = new QueryClient();

ReactDOM.createRoot(document.getElementById("root")!).render(
  <React.StrictMode>
    <QueryClientProvider client={queryClient}>
      <App />
    </QueryClientProvider>
  </React.StrictMode>,
);
`,
    },
    { path: "frontend/src/index.css", description: "Global Tailwind styles", task: "frontend_file", content: TAILWIND_CSS },
    { path: "frontend/src/lib/utils.ts", description: "shadcn cn() helper", task: "frontend_file", content: UTILS },
    { path: "frontend/src/components/ui/button.tsx", description: "shadcn Button", task: "frontend_file", content: BUTTON("@/lib/utils") },
    { path: "frontend/src/components/ui/card.tsx", description: "shadcn Card", task: "frontend_file", content: CARD("@/lib/utils") },
    { path: "frontend/src/components/ui/input.tsx", description: "shadcn Input", task: "frontend_file", content: INPUT("@/lib/utils") },
  ];
}

function nextScaffold(): Scaffold[] {
  return [
    {
      path: "frontend/package.json",
      description: "Next.js dependencies and scripts",
      task: "config_file",
      content: j({
        name: "frontend",
        private: true,
        scripts: { dev: "next dev", build: "next build", start: "next start" },
        dependencies: { next: "14.2.13", react: "^18.3.1", "react-dom": "^18.3.1", ...SHADCN_DEPS },
        devDependencies: {
          "@types/node": "^20.16.5",
          "@types/react": "^18.3.5",
          autoprefixer: "^10.4.20",
          postcss: "^8.4.47",
          tailwindcss: "^3.4.11",
          typescript: "^5.5.3",
        },
      }),
    },
    {
      path: "frontend/next.config.mjs",
      description: "Next.js config with API rewrite",
      task: "config_file",
      content: `/** @type {import('next').NextConfig} */
const nextConfig = {
  async rewrites() {
    return [{ source: "/api/:path*", destination: (process.env.API_URL || "http://localhost:8000") + "/api/:path*" }];
  },
};
export default nextConfig;
`,
    },
    {
      path: "frontend/tsconfig.json",
      description: "TypeScript config",
      task: "config_file",
      content: j({
        compilerOptions: {
          target: "ES2020",
          lib: ["dom", "dom.iterable", "esnext"],
          strict: true,
          noEmit: true,
          module: "esnext",
          moduleResolution: "bundler",
          jsx: "preserve",
          incremental: true,
          skipLibCheck: true,
          plugins: [{ name: "next" }],
          paths: { "@/*": ["./*"] },
        },
        include: ["next-env.d.ts", "**/*.ts", "**/*.tsx"],
        exclude: ["node_modules"],
      }),
    },
    {
      path: "frontend/tailwind.config.ts",
      description: "Tailwind config",
      task: "config_file",
      content: `import type { Config } from "tailwindcss";

export default {
  content: ["./app/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}"],
  theme: { extend: {} },
  plugins: [],
} satisfies Config;
`,
    },
    {
      path: "frontend/postcss.config.mjs",
      description: "PostCSS config",
      task: "config_file",
      content: `export default { plugins: { tailwindcss: {}, autoprefixer: {} } };\n`,
    },
    { path: "frontend/app/globals.css", description: "Global Tailwind styles", task: "frontend_file", content: TAILWIND_CSS },
    { path: "frontend/lib/utils.ts", description: "shadcn cn() helper", task: "frontend_file", content: UTILS },
    { path: "frontend/components/ui/button.tsx", description: "shadcn Button", task: "frontend_file", content: `"use client";\n` + BUTTON("@/lib/utils") },
    { path: "frontend/components/ui/card.tsx", description: "shadcn Card", task: "frontend_file", content: CARD("@/lib/utils") },
    { path: "frontend/components/ui/input.tsx", description: "shadcn Input", task: "frontend_file", content: `"use client";\n` + INPUT("@/lib/utils") },
  ];
}

function htmlScaffold(): Scaffold[] {
  return [
    {
      path: "frontend/css/base.css",
      description: "Reset and base styles",
      task: "frontend_file",
      content: `*,*::before,*::after{box-sizing:border-box}
body{margin:0;font-family:system-ui,-apple-system,Segoe UI,Roboto,sans-serif;line-height:1.5;color:#0f172a;background:#f8fafc}
img{max-width:100%;display:block}
a{color:inherit}
.container{max-width:1100px;margin:0 auto;padding:0 1.25rem}
.btn{display:inline-flex;align-items:center;gap:.5rem;padding:.6rem 1.1rem;border-radius:.5rem;border:0;background:#0f172a;color:#fff;cursor:pointer;font-weight:500}
.btn:hover{background:#1e293b}
.card{background:#fff;border:1px solid #e2e8f0;border-radius:.75rem;padding:1.25rem}
input,textarea,select{font:inherit;padding:.55rem .75rem;border:1px solid #cbd5e1;border-radius:.5rem;width:100%}
`,
    },
    {
      path: "frontend/js/api.js",
      description: "Fetch helper for the backend API",
      task: "frontend_file",
      content: `const API_URL = window.API_URL || "http://localhost:8000";

export async function api(path, options = {}) {
  const res = await fetch(API_URL + path, {
    headers: { "Content-Type": "application/json", ...(options.headers || {}) },
    ...options,
    body: options.body && typeof options.body !== "string" ? JSON.stringify(options.body) : options.body,
  });
  if (!res.ok) throw new Error((await res.text()) || res.statusText);
  return res.status === 204 ? null : res.json();
}
`,
    },
  ];
}

function expressScaffold(db: string): Scaffold[] {
  const dbDeps: Record<string, Record<string, string>> = {
    postgres: { pg: "^8.13.0" },
    supabase: { "@supabase/supabase-js": "^2.45.4" },
    mongodb: { mongoose: "^8.6.3" },
  };
  const dbFile: Record<string, string> = {
    postgres: `import pg from "pg";

export const pool = new pg.Pool({ connectionString: process.env.DATABASE_URL });

export async function query(text, params) {
  const result = await pool.query(text, params);
  return result.rows;
}
`,
    supabase: `import { createClient } from "@supabase/supabase-js";

export const supabase = createClient(process.env.SUPABASE_URL, process.env.SUPABASE_SERVICE_ROLE_KEY, {
  auth: { persistSession: false },
});
`,
    mongodb: `import mongoose from "mongoose";

export async function connectDb() {
  await mongoose.connect(process.env.MONGODB_URI);
  console.log("MongoDB connected");
}
`,
  };
  return [
    {
      path: "server/package.json",
      description: "Backend dependencies and scripts",
      task: "config_file",
      content: j({
        name: "server",
        private: true,
        type: "module",
        scripts: { dev: "node --watch --env-file=.env src/index.js", start: "node src/index.js" },
        dependencies: {
          express: "^4.21.0",
          cors: "^2.8.5",
          helmet: "^7.1.0",
          zod: "^3.23.8",
          jsonwebtoken: "^9.0.2",
          ...dbDeps[db],
        },
      }),
    },
    { path: "server/src/db.js", description: "Database client", task: "backend_file", content: dbFile[db] ?? "" },
    {
      path: "server/src/middleware/error.js",
      description: "Central error handler",
      task: "backend_file",
      content: `export function notFound(req, res) {
  res.status(404).json({ error: "Not found" });
}

export function errorHandler(err, req, res, _next) {
  console.error(err);
  const status = err.status || 500;
  res.status(status).json({ error: status === 500 ? "Internal server error" : err.message });
}
`,
    },
  ];
}

function fastapiScaffold(db: string): Scaffold[] {
  const dbReq: Record<string, string> = {
    postgres: "asyncpg==0.29.0\n",
    supabase: "supabase==2.7.4\n",
    mongodb: "motor==3.6.0\nbeanie==1.26.0\n",
  };
  const dbFile: Record<string, string> = {
    postgres: `import os
import asyncpg

pool: asyncpg.Pool | None = None


async def connect() -> None:
    global pool
    pool = await asyncpg.create_pool(os.environ["DATABASE_URL"])


async def disconnect() -> None:
    if pool:
        await pool.close()
`,
    supabase: `import os
from supabase import create_client, Client

supabase: Client = create_client(os.environ["SUPABASE_URL"], os.environ["SUPABASE_SERVICE_ROLE_KEY"])


async def connect() -> None:
    return None


async def disconnect() -> None:
    return None
`,
    mongodb: `import os
from motor.motor_asyncio import AsyncIOMotorClient

client: AsyncIOMotorClient | None = None


async def connect() -> None:
    global client
    client = AsyncIOMotorClient(os.environ["MONGODB_URI"])


async def disconnect() -> None:
    if client:
        client.close()
`,
  };
  return [
    {
      path: "server/requirements.txt",
      description: "Python dependencies",
      task: "config_file",
      content: `fastapi==0.115.0\nuvicorn[standard]==0.30.6\npydantic==2.9.2\npython-dotenv==1.0.1\npython-jose[cryptography]==3.3.0\n${dbReq[db] ?? ""}`,
    },
    { path: "server/app/db.py", description: "Database connection", task: "backend_file", content: dbFile[db] ?? "" },
  ];
}

export function scaffoldFor(stack: StackOption): Scaffold[] {
  const fe =
    stack.frontendId === "nextjs" ? nextScaffold() : stack.frontendId === "html" ? htmlScaffold() : reactScaffold();
  const be = stack.backendId === "fastapi" ? fastapiScaffold(stack.databaseId) : expressScaffold(stack.databaseId);
  return [...fe, ...be];
}

/** Adds scaffold files to a plan manifest, replacing any model-planned duplicates. */
export function mergeScaffold(files: PlanFile[], stack: StackOption): PlanFile[] {
  const scaffold = scaffoldFor(stack);
  const paths = new Set(scaffold.map((s) => s.path));
  return [
    ...scaffold.map(({ path, description, task }) => ({ path, description, task })),
    ...files.filter((f) => !paths.has(f.path)),
  ];
}

/** Short summary injected into prompts so generated code reuses the scaffold. */
export function scaffoldSummary(stack: StackOption): string {
  return scaffoldFor(stack)
    .map((s) => `- ${s.path}: ${s.description}`)
    .join("\n");
}
