/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NewRouteImport } from './routes/new'
import { Route as PreviewIdRouteImport } from './routes/preview.$id'
import { Route as ProjectIdBuildRouteImport } from './routes/project.$id.build'
import { Route as ProjectIdClarifyRouteImport } from './routes/project.$id.clarify'
import { Route as ProjectIdExportRouteImport } from './routes/project.$id.export'
import { Route as ProjectIdPlanRouteImport } from './routes/project.$id.plan'
import { Route as ProjectIdStackRouteImport } from './routes/project.$id.stack'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewIdRoute = PreviewIdRouteImport.update({
  id: '/preview/$id',
  path: '/preview/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectIdBuildRoute = ProjectIdBuildRouteImport.update({
  id: '/project/$id/build',
  path: '/project/$id/build',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectIdClarifyRoute = ProjectIdClarifyRouteImport.update({
  id: '/project/$id/clarify',
  path: '/project/$id/clarify',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectIdExportRoute = ProjectIdExportRouteImport.update({
  id: '/project/$id/export',
  path: '/project/$id/export',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectIdPlanRoute = ProjectIdPlanRouteImport.update({
  id: '/project/$id/plan',
  path: '/project/$id/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectIdStackRoute = ProjectIdStackRouteImport.update({
  id: '/project/$id/stack',
  path: '/project/$id/stack',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/new': typeof NewRoute
  '/preview/$id': typeof PreviewIdRoute
  '/project/$id/build': typeof ProjectIdBuildRoute
  '/project/$id/clarify': typeof ProjectIdClarifyRoute
  '/project/$id/export': typeof ProjectIdExportRoute
  '/project/$id/plan': typeof ProjectIdPlanRoute
  '/project/$id/stack': typeof ProjectIdStackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/new': typeof NewRoute
  '/preview/$id': typeof PreviewIdRoute
  '/project/$id/build': typeof ProjectIdBuildRoute
  '/project/$id/clarify': typeof ProjectIdClarifyRoute
  '/project/$id/export': typeof ProjectIdExportRoute
  '/project/$id/plan': typeof ProjectIdPlanRoute
  '/project/$id/stack': typeof ProjectIdStackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/new': typeof NewRoute
  '/preview/$id': typeof PreviewIdRoute
  '/project/$id/build': typeof ProjectIdBuildRoute
  '/project/$id/clarify': typeof ProjectIdClarifyRoute
  '/project/$id/export': typeof ProjectIdExportRoute
  '/project/$id/plan': typeof ProjectIdPlanRoute
  '/project/$id/stack': typeof ProjectIdStackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/new'
    | '/preview/$id'
    | '/project/$id/build'
    | '/project/$id/clarify'
    | '/project/$id/export'
    | '/project/$id/plan'
    | '/project/$id/stack'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/new'
    | '/preview/$id'
    | '/project/$id/build'
    | '/project/$id/clarify'
    | '/project/$id/export'
    | '/project/$id/plan'
    | '/project/$id/stack'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/new'
    | '/preview/$id'
    | '/project/$id/build'
    | '/project/$id/clarify'
    | '/project/$id/export'
    | '/project/$id/plan'
    | '/project/$id/stack'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  NewRoute: typeof NewRoute
  PreviewIdRoute: typeof PreviewIdRoute
  ProjectIdBuildRoute: typeof ProjectIdBuildRoute
  ProjectIdClarifyRoute: typeof ProjectIdClarifyRoute
  ProjectIdExportRoute: typeof ProjectIdExportRoute
  ProjectIdPlanRoute: typeof ProjectIdPlanRoute
  ProjectIdStackRoute: typeof ProjectIdStackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview/$id': {
      id: '/preview/$id'
      path: '/preview/$id'
      fullPath: '/preview/$id'
      preLoaderRoute: typeof PreviewIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/$id/build': {
      id: '/project/$id/build'
      path: '/project/$id/build'
      fullPath: '/project/$id/build'
      preLoaderRoute: typeof ProjectIdBuildRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/$id/clarify': {
      id: '/project/$id/clarify'
      path: '/project/$id/clarify'
      fullPath: '/project/$id/clarify'
      preLoaderRoute: typeof ProjectIdClarifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/$id/export': {
      id: '/project/$id/export'
      path: '/project/$id/export'
      fullPath: '/project/$id/export'
      preLoaderRoute: typeof ProjectIdExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/$id/plan': {
      id: '/project/$id/plan'
      path: '/project/$id/plan'
      fullPath: '/project/$id/plan'
      preLoaderRoute: typeof ProjectIdPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/$id/stack': {
      id: '/project/$id/stack'
      path: '/project/$id/stack'
      fullPath: '/project/$id/stack'
      preLoaderRoute: typeof ProjectIdStackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  NewRoute: NewRoute,
  PreviewIdRoute: PreviewIdRoute,
  ProjectIdBuildRoute: ProjectIdBuildRoute,
  ProjectIdClarifyRoute: ProjectIdClarifyRoute,
  ProjectIdExportRoute: ProjectIdExportRoute,
  ProjectIdPlanRoute: ProjectIdPlanRoute,
  ProjectIdStackRoute: ProjectIdStackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
